name: run spec-parser

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: get spec-parser
        run: |
          git clone --depth=1 --single-branch --branch=main https://github.com/spdx/spec-parser/
          cd spec-parser
          python3 -m pip install -r requirements.txt
          python main.py -h
      - name: run spec-parser
        run: |
          cd spec-parser
          mkdir -p  /tmp/spec-parser.out
          python main.py \
              --gen-md \
              --gen-refs \
              --gen-rdf \
              --out-dir /tmp/spec-parser.out \
              ../model

      - uses: actions/upload-artifact@v3
        with:
          name: model.ttl
          path: /tmp/spec-parser.out/model.ttl
          
      - name: get Ontospy
        run: |
          git clone --depth=1 --single-branch --branch=master https://github.com/lambdamusic/Ontospy.git
          cd Ontospy
          python3 -m pip install -r requirements.txt
          python3 -m pip install -e .
      - name: generate docs with Ontospy
        run : |
          cd Ontospy
          mkdir -p /tmp/generated_docs
          ontospy gendocs -o /tmp/generated_docs --type 2 --title SPDX-3.0 /tmp/spec-parser.out/model.ttl

      - uses: actions/upload-artifact@v3
        with:
          name: generated_docs
          path: /tmp/generated_docs
          
      - name: commit changes to branch 
        run: |
          if [ ${{ github.ref_name }} == "main" ]
          then
            git fetch 
            git checkout gh-pages
            cp /tmp/spec-parser.out/model.ttl .
            cp -r /tmp/generated_docs/ .
            git add model.ttl generated_docs/ 
            git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -s -m "Automated Upload" --author "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
            git push origin
          fi
